package com.lsz.persistence.sequence;

import com.lsz.persistence.AuditableDo;

public class SequenceDo extends AuditableDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.id
     *
     * @mbg.generated
     */
    private Long id;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.value
     *
     * @mbg.generated
     */
    private Long value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sequence
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.id
     *
     * @return the value of sequence.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.id
     *
     * @param id the value for sequence.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.name
     *
     * @return the value of sequence.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.name
     *
     * @param name the value for sequence.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.value
     *
     * @return the value of sequence.value
     *
     * @mbg.generated
     */
    public Long getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.value
     *
     * @param value the value for sequence.value
     *
     * @mbg.generated
     */
    public void setValue(Long value) {
        this.value = value;
    }



}